--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: RSpec::Core::MockFrameworkAdapter::configuration
is_singleton: true
name: configuration
params: ()
visibility: public
