--- !ruby/object:RI::ClassDescription 
attributes: 
- !ruby/object:RI::Attribute 
  comment: 
  name: options
  rw: R
class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@private"
constants: 
- !ruby/object:RI::Constant 
  comment: 
  name: NON_FORCED_OPTIONS
  value: "[         :debug, :requires, :libs, :profile, :drb, :files_or_directories_to_run,         :line_numbers, :full_description, :full_backtrace, :tty"
- !ruby/object:RI::Constant 
  comment: 
  name: MERGED_OPTIONS
  value: "[:requires, :libs].to_set"
full_name: RSpec::Core::ConfigurationOptions
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: configure
- !ruby/object:RI::MethodSummary 
  name: drb_argv
- !ruby/object:RI::MethodSummary 
  name: filter_manager
- !ruby/object:RI::MethodSummary 
  name: parse_options
name: ConfigurationOptions
superclass: Object
