--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@deprecated use RSpec.configure instead."
full_name: RSpec::Runner::configure
is_singleton: true
name: configure
params: (&block)
visibility: public
