--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: RSpec::Core::Configuration::MustBeConfiguredBeforeExampleGroupsError
includes: []

instance_methods: []

name: MustBeConfiguredBeforeExampleGroupsError
superclass: StandardError
