--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: Provides configuration options for rspec-mocks.
constants: []

full_name: RSpec::Mocks::Configuration
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: add_stub_and_should_receive_to
name: Configuration
superclass: Object
