--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: RSpec::Core::Metadata#configure_for_example
is_singleton: false
name: configure_for_example
params: (description, user_metadata)
visibility: protected
