--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:SM::Flow::P 
  body: Rack::Config modifies the environment using the block given during initialization.
- !ruby/struct:SM::Flow::P 
  body: "Example:"
- !ruby/struct:SM::Flow::VERB 
  body: "    use Rack::Config do |env|\n      env['my-key'] = 'some-value'\n    end\n"
constants: []

full_name: Rack::Config
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: call
name: Config
superclass: Object
