--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@private"
full_name: RSpec::Core::Configuration#configure_expectation_framework
is_singleton: false
name: configure_expectation_framework
params: ()
visibility: public
