--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@private"
- !ruby/struct:SM::Flow::P 
  body: Used internally to extend a group with modules using `include` and/or `extend`.
full_name: RSpec::Core::Configuration#configure_group
is_singleton: false
name: configure_group
params: (group)
visibility: public
