--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: "@private"
constants: []

full_name: RSpec::Core::MetadataHashBuilder::WithConfigWarning
includes: 
- !ruby/object:RI::IncludedModule 
  name: Common
instance_methods: []

name: WithConfigWarning
superclass: 
