--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Returns the global [Configuration](RSpec/Core/Configuration) object. While you <em>can</em> use this method to access the configuration, the more common convention is to use [RSpec.configure](RSpec#configure-class_method).
- !ruby/struct:SM::Flow::P 
  body: "@example"
- !ruby/struct:SM::Flow::VERB 
  body: "    RSpec.configuration.drb_port = 1234\n"
- !ruby/struct:SM::Flow::P 
  body: "@see RSpec.configure @see Core::Configuration"
full_name: RSpec::configuration
is_singleton: true
name: configuration
params: ()
visibility: public
