--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: configuration if block_given?
comment: 
- !ruby/struct:SM::Flow::P 
  body: Yields the global configuration to a block. @yield [Configuration] global configuration
- !ruby/struct:SM::Flow::P 
  body: "@example"
- !ruby/struct:SM::Flow::VERB 
  body: "    RSpec.configure do |config|\n      config.add_formatter 'documentation'\n    end\n"
- !ruby/struct:SM::Flow::P 
  body: "@see Core::Configuration"
full_name: RSpec::configure
is_singleton: true
name: configure
params: () {|configuration if block_given?| ...}
visibility: public
