"""add columns to achievement

Revision ID: 466668de7dee
Revises: 19b2d915e52a
Create Date: 2013-03-05 13:37:24.758075

"""

# revision identifiers, used by Alembic.
revision = '466668de7dee'
down_revision = '19b2d915e52a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM unlocked_achievements")
    op.execute("DELETE FROM achievements")
    op.add_column('achievements', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('achievements', sa.Column('metric', sa.String(length=32), nullable=True))
    op.add_column('achievements', sa.Column('activity', sa.String(length=32), nullable=True))
    op.add_column('achievements', sa.Column('operator', sa.String(length=32), nullable=True))
    op.add_column('achievements', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('achievements', sa.Column('quantity', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    pass
