"""Added goals table

Revision ID: b463f0358d6
Revises: 2cde2eaa65c7
Create Date: 2013-02-21 15:28:52.746932

"""

# revision identifiers, used by Alembic.
revision = 'b463f0358d6'
down_revision = '2cde2eaa65c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=32), nullable=True),
    sa.Column('operator', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('metric', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    ### end Alembic commands ###


def downgrade():
    pass
