
var target = UIATarget.localTarget();
target.frontMostApp().navigationBar().rightButton().tap();
target.frontMostApp().mainWindow().textFields()["userNameLogin"].tap();
target.frontMostApp().keyboard().typeString("ben");
target.frontMostApp().mainWindow().secureTextFields()["passwordLogin"].tap();
target.frontMostApp().keyboard().typeString("ben");
target.frontMostApp().mainWindow().buttons()["Login"].tap();
target.waitForInvalid();
target.pushTimeout(5);
target.frontMostApp().navigationBar().leftButton().tap();
target.popTimeout();
target.frontMostApp().navigationBar().rightButton().tap();
target.frontMostApp().navigationBar().leftButton().tap();
target.frontMostApp().navigationBar().rightButton().tap();
target.frontMostApp().mainWindow().textFields()["userNameLogin"].tap();
target.frontMostApp().keyboard().typeString("ben");
target.tap({x:351.00, y:223.00});
target.frontMostApp().mainWindow().secureTextFields()["passwordLogin"].tap();
target.frontMostApp().keyboard().typeString("ben\n");
target.frontMostApp().tabBar().buttons()["Profile"].tap();
target.frontMostApp().mainWindow().tableViews()[1].cells()["Runner"].staticTexts()["Runner"].scrollToVisible();
target.frontMostApp().mainWindow().tableViews()[1].cells()["Forrest Gump"].staticTexts()["Forrest Gump"].scrollToVisible();
target.frontMostApp().tabBar().buttons()["Activities"].tap();
target.frontMostApp().tabBar().buttons()["Profile"].tap();
target.frontMostApp().tabBar().buttons()["Activities"].tap();
target.frontMostApp().tabBar().buttons()["Goals"].tap();
target.frontMostApp().tabBar().buttons()["Events"].tap();
target.frontMostApp().tabBar().buttons()["Health"].tap();
target.frontMostApp().tabBar().buttons()["Stats"].tap();
target.frontMostApp().tabBar().buttons()["About"].tap();
target.frontMostApp().tabBar().buttons()["Stats"].tap();
target.frontMostApp().tabBar().buttons()["Health"].tap();
target.frontMostApp().tabBar().buttons()["Events"].tap();
target.frontMostApp().tabBar().buttons()["Goals"].tap();
target.frontMostApp().tabBar().buttons()["Activities"].tap();
target.frontMostApp().tabBar().buttons()["Profile"].tap();
target.frontMostApp().tabBar().buttons()["Home"].tap();
target.frontMostApp().navigationBar().leftButton().tap();

UIALogger.logPass("TestLogin");